// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package session_stats

import (
	"context"
	"fmt"
	"io"

	api "go.fd.io/govpp/api"
	memclnt "go.fd.io/govpp/binapi/memclnt"
)

// RPCService defines RPC service session_stats.
type RPCService interface {
	SfdpSessionStatsClear(ctx context.Context, in *SfdpSessionStatsClear) (*SfdpSessionStatsClearReply, error)
	SfdpSessionStatsClearCustomAPIData(ctx context.Context, in *SfdpSessionStatsClearCustomAPIData) (*SfdpSessionStatsClearCustomAPIDataReply, error)
	SfdpSessionStatsDump(ctx context.Context, in *SfdpSessionStatsDump) (RPCService_SfdpSessionStatsDumpClient, error)
	SfdpSessionStatsExportNow(ctx context.Context, in *SfdpSessionStatsExportNow) (*SfdpSessionStatsExportNowReply, error)
	SfdpSessionStatsGetConfig(ctx context.Context, in *SfdpSessionStatsGetConfig) (*SfdpSessionStatsGetConfigReply, error)
	SfdpSessionStatsGetTenantCustomData(ctx context.Context, in *SfdpSessionStatsGetTenantCustomData) (*SfdpSessionStatsGetTenantCustomDataReply, error)
	SfdpSessionStatsPeriodicExport(ctx context.Context, in *SfdpSessionStatsPeriodicExport) (*SfdpSessionStatsPeriodicExportReply, error)
	SfdpSessionStatsRingEnable(ctx context.Context, in *SfdpSessionStatsRingEnable) (*SfdpSessionStatsRingEnableReply, error)
	SfdpSessionStatsRingEntryAbiID(ctx context.Context, in *SfdpSessionStatsRingEntryAbiID) (*SfdpSessionStatsRingEntryAbiIDReply, error)
	SfdpSessionStatsSetCustomAPIData(ctx context.Context, in *SfdpSessionStatsSetCustomAPIData) (*SfdpSessionStatsSetCustomAPIDataReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) SfdpSessionStatsClear(ctx context.Context, in *SfdpSessionStatsClear) (*SfdpSessionStatsClearReply, error) {
	out := new(SfdpSessionStatsClearReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) SfdpSessionStatsClearCustomAPIData(ctx context.Context, in *SfdpSessionStatsClearCustomAPIData) (*SfdpSessionStatsClearCustomAPIDataReply, error) {
	out := new(SfdpSessionStatsClearCustomAPIDataReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) SfdpSessionStatsDump(ctx context.Context, in *SfdpSessionStatsDump) (RPCService_SfdpSessionStatsDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_SfdpSessionStatsDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_SfdpSessionStatsDumpClient interface {
	Recv() (*SfdpSessionStatsDetails, error)
	api.Stream
}

type serviceClient_SfdpSessionStatsDumpClient struct {
	api.Stream
}

func (c *serviceClient_SfdpSessionStatsDumpClient) Recv() (*SfdpSessionStatsDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *SfdpSessionStatsDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) SfdpSessionStatsExportNow(ctx context.Context, in *SfdpSessionStatsExportNow) (*SfdpSessionStatsExportNowReply, error) {
	out := new(SfdpSessionStatsExportNowReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) SfdpSessionStatsGetConfig(ctx context.Context, in *SfdpSessionStatsGetConfig) (*SfdpSessionStatsGetConfigReply, error) {
	out := new(SfdpSessionStatsGetConfigReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) SfdpSessionStatsGetTenantCustomData(ctx context.Context, in *SfdpSessionStatsGetTenantCustomData) (*SfdpSessionStatsGetTenantCustomDataReply, error) {
	out := new(SfdpSessionStatsGetTenantCustomDataReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) SfdpSessionStatsPeriodicExport(ctx context.Context, in *SfdpSessionStatsPeriodicExport) (*SfdpSessionStatsPeriodicExportReply, error) {
	out := new(SfdpSessionStatsPeriodicExportReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) SfdpSessionStatsRingEnable(ctx context.Context, in *SfdpSessionStatsRingEnable) (*SfdpSessionStatsRingEnableReply, error) {
	out := new(SfdpSessionStatsRingEnableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) SfdpSessionStatsRingEntryAbiID(ctx context.Context, in *SfdpSessionStatsRingEntryAbiID) (*SfdpSessionStatsRingEntryAbiIDReply, error) {
	out := new(SfdpSessionStatsRingEntryAbiIDReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) SfdpSessionStatsSetCustomAPIData(ctx context.Context, in *SfdpSessionStatsSetCustomAPIData) (*SfdpSessionStatsSetCustomAPIDataReply, error) {
	out := new(SfdpSessionStatsSetCustomAPIDataReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
