// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: c755955
//  VPP:              26.06-rc0~246-ga5f38d97d
// source: plugins/session_stats.api.json

// Package session_stats contains generated bindings for API file session_stats.api.
//
// Contents:
// -  1 struct
// - 20 messages
package session_stats

import (
	api "go.fd.io/govpp/api"
	_ "go.fd.io/govpp/binapi/interface_types"
	ip_types "go.fd.io/govpp/binapi/ip_types"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "session_stats"
	APIVersion = "1.1.0"
	VersionCrc = 0x4e43ef8b
)

// SfdpSessionStatsRingEntry defines type 'sfdp_session_stats_ring_entry'.
type SfdpSessionStatsRingEntry struct {
	Duration                   float64 `binapi:"f64,name=duration" json:"duration,omitempty"`
	TTLMeanForward             float64 `binapi:"f64,name=ttl_mean_forward" json:"ttl_mean_forward,omitempty"`
	TTLMeanReverse             float64 `binapi:"f64,name=ttl_mean_reverse" json:"ttl_mean_reverse,omitempty"`
	TTLStddevForward           float64 `binapi:"f64,name=ttl_stddev_forward" json:"ttl_stddev_forward,omitempty"`
	TTLStddevReverse           float64 `binapi:"f64,name=ttl_stddev_reverse" json:"ttl_stddev_reverse,omitempty"`
	RttMeanForward             float64 `binapi:"f64,name=rtt_mean_forward" json:"rtt_mean_forward,omitempty"`
	RttMeanReverse             float64 `binapi:"f64,name=rtt_mean_reverse" json:"rtt_mean_reverse,omitempty"`
	RttStddevForward           float64 `binapi:"f64,name=rtt_stddev_forward" json:"rtt_stddev_forward,omitempty"`
	RttStddevReverse           float64 `binapi:"f64,name=rtt_stddev_reverse" json:"rtt_stddev_reverse,omitempty"`
	SessionID                  uint64  `binapi:"u64,name=session_id" json:"session_id,omitempty"`
	PacketsForward             uint64  `binapi:"u64,name=packets_forward" json:"packets_forward,omitempty"`
	PacketsReverse             uint64  `binapi:"u64,name=packets_reverse" json:"packets_reverse,omitempty"`
	BytesForward               uint64  `binapi:"u64,name=bytes_forward" json:"bytes_forward,omitempty"`
	BytesReverse               uint64  `binapi:"u64,name=bytes_reverse" json:"bytes_reverse,omitempty"`
	Opaque                     uint64  `binapi:"u64,name=opaque" json:"opaque,omitempty"`
	SessionIndex               uint32  `binapi:"u32,name=session_index" json:"session_index,omitempty"`
	TenantID                   uint32  `binapi:"u32,name=tenant_id" json:"tenant_id,omitempty"`
	TCPSynPackets              uint32  `binapi:"u32,name=tcp_syn_packets" json:"tcp_syn_packets,omitempty"`
	TCPFinPackets              uint32  `binapi:"u32,name=tcp_fin_packets" json:"tcp_fin_packets,omitempty"`
	TCPRstPackets              uint32  `binapi:"u32,name=tcp_rst_packets" json:"tcp_rst_packets,omitempty"`
	TCPEcnEctPackets           uint32  `binapi:"u32,name=tcp_ecn_ect_packets" json:"tcp_ecn_ect_packets,omitempty"`
	TCPEcnCePackets            uint32  `binapi:"u32,name=tcp_ecn_ce_packets" json:"tcp_ecn_ce_packets,omitempty"`
	TCPEcePackets              uint32  `binapi:"u32,name=tcp_ece_packets" json:"tcp_ece_packets,omitempty"`
	TCPCwrPackets              uint32  `binapi:"u32,name=tcp_cwr_packets" json:"tcp_cwr_packets,omitempty"`
	TCPRetransmissionsFwd      uint32  `binapi:"u32,name=tcp_retransmissions_fwd" json:"tcp_retransmissions_fwd,omitempty"`
	TCPRetransmissionsRev      uint32  `binapi:"u32,name=tcp_retransmissions_rev" json:"tcp_retransmissions_rev,omitempty"`
	TCPZeroWindowEventsFwd     uint32  `binapi:"u32,name=tcp_zero_window_events_fwd" json:"tcp_zero_window_events_fwd,omitempty"`
	TCPZeroWindowEventsRev     uint32  `binapi:"u32,name=tcp_zero_window_events_rev" json:"tcp_zero_window_events_rev,omitempty"`
	TCPDupackEventsFwd         uint32  `binapi:"u32,name=tcp_dupack_events_fwd" json:"tcp_dupack_events_fwd,omitempty"`
	TCPDupackEventsRev         uint32  `binapi:"u32,name=tcp_dupack_events_rev" json:"tcp_dupack_events_rev,omitempty"`
	TCPPartialOverlapEventsFwd uint32  `binapi:"u32,name=tcp_partial_overlap_events_fwd" json:"tcp_partial_overlap_events_fwd,omitempty"`
	TCPPartialOverlapEventsRev uint32  `binapi:"u32,name=tcp_partial_overlap_events_rev" json:"tcp_partial_overlap_events_rev,omitempty"`
	TCPOutOfOrderEventsFwd     uint32  `binapi:"u32,name=tcp_out_of_order_events_fwd" json:"tcp_out_of_order_events_fwd,omitempty"`
	TCPOutOfOrderEventsRev     uint32  `binapi:"u32,name=tcp_out_of_order_events_rev" json:"tcp_out_of_order_events_rev,omitempty"`
	TCPLastSeqForward          uint32  `binapi:"u32,name=tcp_last_seq_forward" json:"tcp_last_seq_forward,omitempty"`
	TCPLastAckForward          uint32  `binapi:"u32,name=tcp_last_ack_forward" json:"tcp_last_ack_forward,omitempty"`
	TCPLastSeqReverse          uint32  `binapi:"u32,name=tcp_last_seq_reverse" json:"tcp_last_seq_reverse,omitempty"`
	TCPLastAckReverse          uint32  `binapi:"u32,name=tcp_last_ack_reverse" json:"tcp_last_ack_reverse,omitempty"`
	SrcPort                    uint16  `binapi:"u16,name=src_port" json:"src_port,omitempty"`
	DstPort                    uint16  `binapi:"u16,name=dst_port" json:"dst_port,omitempty"`
	TCPMss                     uint16  `binapi:"u16,name=tcp_mss" json:"tcp_mss,omitempty"`
	Proto                      uint8   `binapi:"u8,name=proto" json:"proto,omitempty"`
	SessionType                uint8   `binapi:"u8,name=session_type" json:"session_type,omitempty"`
	IsIP4                      uint8   `binapi:"u8,name=is_ip4" json:"is_ip4,omitempty"`
	TTLMinForward              uint8   `binapi:"u8,name=ttl_min_forward" json:"ttl_min_forward,omitempty"`
	TTLMaxForward              uint8   `binapi:"u8,name=ttl_max_forward" json:"ttl_max_forward,omitempty"`
	TTLMinReverse              uint8   `binapi:"u8,name=ttl_min_reverse" json:"ttl_min_reverse,omitempty"`
	TTLMaxReverse              uint8   `binapi:"u8,name=ttl_max_reverse" json:"ttl_max_reverse,omitempty"`
	SrcIP                      []byte  `binapi:"u8[16],name=src_ip" json:"src_ip,omitempty"`
	DstIP                      []byte  `binapi:"u8[16],name=dst_ip" json:"dst_ip,omitempty"`
	TCPHandshakeComplete       uint8   `binapi:"u8,name=tcp_handshake_complete" json:"tcp_handshake_complete,omitempty"`
}

// * @brief Clear all session stats
//   - - session_id - specific session to clear (0xFFFFFFFF = all sessions)
//
// SfdpSessionStatsClear defines message 'sfdp_session_stats_clear'.
type SfdpSessionStatsClear struct {
	SessionID uint64 `binapi:"u64,name=session_id,default=0" json:"session_id,omitempty"`
}

func (m *SfdpSessionStatsClear) Reset()               { *m = SfdpSessionStatsClear{} }
func (*SfdpSessionStatsClear) GetMessageName() string { return "sfdp_session_stats_clear" }
func (*SfdpSessionStatsClear) GetCrcString() string   { return "350f1aaa" }
func (*SfdpSessionStatsClear) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpSessionStatsClear) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 8 // m.SessionID
	return size
}
func (m *SfdpSessionStatsClear) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint64(m.SessionID)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsClear) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SessionID = buf.DecodeUint64()
	return nil
}

// * @brief Clear custom API data for a tenant
//   - - tenant_id - tenant ID (customer-specified value) to clear custom data for (0xFFFFFFFF = clear all tenants)
//
// SfdpSessionStatsClearCustomAPIData defines message 'sfdp_session_stats_clear_custom_api_data'.
type SfdpSessionStatsClearCustomAPIData struct {
	TenantID uint32 `binapi:"u32,name=tenant_id,default=4294967295" json:"tenant_id,omitempty"`
}

func (m *SfdpSessionStatsClearCustomAPIData) Reset() { *m = SfdpSessionStatsClearCustomAPIData{} }
func (*SfdpSessionStatsClearCustomAPIData) GetMessageName() string {
	return "sfdp_session_stats_clear_custom_api_data"
}
func (*SfdpSessionStatsClearCustomAPIData) GetCrcString() string { return "09d55da7" }
func (*SfdpSessionStatsClearCustomAPIData) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpSessionStatsClearCustomAPIData) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.TenantID
	return size
}
func (m *SfdpSessionStatsClearCustomAPIData) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TenantID)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsClearCustomAPIData) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TenantID = buf.DecodeUint32()
	return nil
}

// SfdpSessionStatsClearCustomAPIDataReply defines message 'sfdp_session_stats_clear_custom_api_data_reply'.
type SfdpSessionStatsClearCustomAPIDataReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *SfdpSessionStatsClearCustomAPIDataReply) Reset() {
	*m = SfdpSessionStatsClearCustomAPIDataReply{}
}
func (*SfdpSessionStatsClearCustomAPIDataReply) GetMessageName() string {
	return "sfdp_session_stats_clear_custom_api_data_reply"
}
func (*SfdpSessionStatsClearCustomAPIDataReply) GetCrcString() string { return "e8d4e804" }
func (*SfdpSessionStatsClearCustomAPIDataReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpSessionStatsClearCustomAPIDataReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *SfdpSessionStatsClearCustomAPIDataReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsClearCustomAPIDataReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// SfdpSessionStatsClearReply defines message 'sfdp_session_stats_clear_reply'.
type SfdpSessionStatsClearReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *SfdpSessionStatsClearReply) Reset()               { *m = SfdpSessionStatsClearReply{} }
func (*SfdpSessionStatsClearReply) GetMessageName() string { return "sfdp_session_stats_clear_reply" }
func (*SfdpSessionStatsClearReply) GetCrcString() string   { return "e8d4e804" }
func (*SfdpSessionStatsClearReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpSessionStatsClearReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *SfdpSessionStatsClearReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsClearReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// * @brief Session stats entry with extended statistics
//   - - session_id - the SFDP session ID
//   - - session_version - session version for stale detection
//   - - tenant_idx - tenant index
//   - - proto - IP protocol (6=TCP, 17=UDP, etc.)
//   - - is_ip6 - 1 if IPv6, 0 if IPv4
//   - - src_addr - source IP address
//   - - dst_addr - destination IP address
//   - - src_port - source port
//   - - dst_port - destination port
//   - - packets_fwd - packets in forward direction
//   - - packets_rev - packets in reverse direction
//   - - bytes_fwd - bytes in forward direction
//   - - bytes_rev - bytes in reverse direction
//   - - first_seen - timestamp when session was first seen
//   - - last_seen - timestamp when session was last seen
//   - - duration - session duration in seconds
//   - - ttl_min_fwd - TTL min forward direction
//   - - ttl_max_fwd - TTL max forward direction
//   - - ttl_mean_fwd - TTL mean forward direction
//   - - ttl_stddev_fwd - TTL standard deviation forward direction
//   - - ttl_min_rev - TTL min reverse direction
//   - - ttl_max_rev - TTL max reverse direction
//   - - ttl_mean_rev - TTL mean reverse direction
//   - - ttl_stddev_rev - TTL standard deviation reverse direction
//   - - rtt_mean_fwd - RTT mean forward direction
//   - - rtt_stddev_fwd - RTT standard deviation forward direction
//   - - rtt_mean_rev - RTT mean reverse direction
//   - - rtt_stddev_rev - RTT standard deviation reverse direction
//   - - tcp_mss - TCP MSS from SYN options (TCP only)
//   - - tcp_handshake_complete - TCP 3-way handshake completed (TCP only)
//   - - tcp_syn_packets - TCP SYN packets counter (TCP only)
//   - - tcp_fin_packets - TCP FIN packets counter (TCP only)
//   - - tcp_rst_packets - TCP RST packets counter (TCP only)
//   - - tcp_ecn_ect_packets - TCP ECN ECT marked packets (TCP only)
//   - - tcp_ecn_ce_packets - TCP ECN CE marked packets (TCP only)
//   - - tcp_ece_packets - TCP ECE flag packets (TCP only)
//   - - tcp_cwr_packets - TCP CWR flag packets (TCP only)
//   - - tcp_retransmissions_fwd - TCP retransmission events forward (TCP only)
//   - - tcp_retransmissions_rev - TCP retransmission events reverse (TCP only)
//   - - tcp_zero_window_events_fwd - TCP zero window events forward (TCP only)
//   - - tcp_zero_window_events_rev - TCP zero window events reverse (TCP only)
//   - - tcp_dupack_events_fwd - TCP duplicate ACK events forward (TCP only)
//   - - tcp_dupack_events_rev - TCP duplicate ACK events reverse (TCP only)
//   - - tcp_partial_overlap_events_fwd - TCP partial overlap events forward (TCP only)
//   - - tcp_partial_overlap_events_rev - TCP partial overlap events reverse (TCP only)
//   - - tcp_out_of_order_events_fwd - TCP out-of-order events forward (TCP only)
//   - - tcp_out_of_order_events_rev - TCP out-of-order events reverse (TCP only)
//   - - tcp_last_seq_fwd - TCP last sequence number forward (TCP only)
//   - - tcp_last_ack_fwd - TCP last ACK number forward (TCP only)
//   - - tcp_last_seq_rev - TCP last sequence number reverse (TCP only)
//   - - tcp_last_ack_rev - TCP last ACK number reverse (TCP only)
//
// SfdpSessionStatsDetails defines message 'sfdp_session_stats_details'.
type SfdpSessionStatsDetails struct {
	SrcAddr                    ip_types.Address `binapi:"address,name=src_addr" json:"src_addr,omitempty"`
	DstAddr                    ip_types.Address `binapi:"address,name=dst_addr" json:"dst_addr,omitempty"`
	FirstSeen                  float64          `binapi:"f64,name=first_seen" json:"first_seen,omitempty"`
	LastSeen                   float64          `binapi:"f64,name=last_seen" json:"last_seen,omitempty"`
	Duration                   float64          `binapi:"f64,name=duration" json:"duration,omitempty"`
	TTLMeanFwd                 float64          `binapi:"f64,name=ttl_mean_fwd" json:"ttl_mean_fwd,omitempty"`
	TTLMeanRev                 float64          `binapi:"f64,name=ttl_mean_rev" json:"ttl_mean_rev,omitempty"`
	TTLStddevFwd               float64          `binapi:"f64,name=ttl_stddev_fwd" json:"ttl_stddev_fwd,omitempty"`
	TTLStddevRev               float64          `binapi:"f64,name=ttl_stddev_rev" json:"ttl_stddev_rev,omitempty"`
	RttMeanFwd                 float64          `binapi:"f64,name=rtt_mean_fwd" json:"rtt_mean_fwd,omitempty"`
	RttMeanRev                 float64          `binapi:"f64,name=rtt_mean_rev" json:"rtt_mean_rev,omitempty"`
	RttStddevFwd               float64          `binapi:"f64,name=rtt_stddev_fwd" json:"rtt_stddev_fwd,omitempty"`
	RttStddevRev               float64          `binapi:"f64,name=rtt_stddev_rev" json:"rtt_stddev_rev,omitempty"`
	PacketsFwd                 uint64           `binapi:"u64,name=packets_fwd" json:"packets_fwd,omitempty"`
	PacketsRev                 uint64           `binapi:"u64,name=packets_rev" json:"packets_rev,omitempty"`
	BytesFwd                   uint64           `binapi:"u64,name=bytes_fwd" json:"bytes_fwd,omitempty"`
	BytesRev                   uint64           `binapi:"u64,name=bytes_rev" json:"bytes_rev,omitempty"`
	SessionID                  uint64           `binapi:"u64,name=session_id" json:"session_id,omitempty"`
	TCPSynPackets              uint32           `binapi:"u32,name=tcp_syn_packets" json:"tcp_syn_packets,omitempty"`
	TCPFinPackets              uint32           `binapi:"u32,name=tcp_fin_packets" json:"tcp_fin_packets,omitempty"`
	TCPRstPackets              uint32           `binapi:"u32,name=tcp_rst_packets" json:"tcp_rst_packets,omitempty"`
	TCPEcnEctPackets           uint32           `binapi:"u32,name=tcp_ecn_ect_packets" json:"tcp_ecn_ect_packets,omitempty"`
	TCPEcnCePackets            uint32           `binapi:"u32,name=tcp_ecn_ce_packets" json:"tcp_ecn_ce_packets,omitempty"`
	TCPEcePackets              uint32           `binapi:"u32,name=tcp_ece_packets" json:"tcp_ece_packets,omitempty"`
	TCPCwrPackets              uint32           `binapi:"u32,name=tcp_cwr_packets" json:"tcp_cwr_packets,omitempty"`
	TCPRetransmissionsFwd      uint32           `binapi:"u32,name=tcp_retransmissions_fwd" json:"tcp_retransmissions_fwd,omitempty"`
	TCPRetransmissionsRev      uint32           `binapi:"u32,name=tcp_retransmissions_rev" json:"tcp_retransmissions_rev,omitempty"`
	TCPZeroWindowEventsFwd     uint32           `binapi:"u32,name=tcp_zero_window_events_fwd" json:"tcp_zero_window_events_fwd,omitempty"`
	TCPZeroWindowEventsRev     uint32           `binapi:"u32,name=tcp_zero_window_events_rev" json:"tcp_zero_window_events_rev,omitempty"`
	TCPDupackEventsFwd         uint32           `binapi:"u32,name=tcp_dupack_events_fwd" json:"tcp_dupack_events_fwd,omitempty"`
	TCPDupackEventsRev         uint32           `binapi:"u32,name=tcp_dupack_events_rev" json:"tcp_dupack_events_rev,omitempty"`
	TCPPartialOverlapEventsFwd uint32           `binapi:"u32,name=tcp_partial_overlap_events_fwd" json:"tcp_partial_overlap_events_fwd,omitempty"`
	TCPPartialOverlapEventsRev uint32           `binapi:"u32,name=tcp_partial_overlap_events_rev" json:"tcp_partial_overlap_events_rev,omitempty"`
	TCPOutOfOrderEventsFwd     uint32           `binapi:"u32,name=tcp_out_of_order_events_fwd" json:"tcp_out_of_order_events_fwd,omitempty"`
	TCPOutOfOrderEventsRev     uint32           `binapi:"u32,name=tcp_out_of_order_events_rev" json:"tcp_out_of_order_events_rev,omitempty"`
	TCPLastSeqFwd              uint32           `binapi:"u32,name=tcp_last_seq_fwd" json:"tcp_last_seq_fwd,omitempty"`
	TCPLastAckFwd              uint32           `binapi:"u32,name=tcp_last_ack_fwd" json:"tcp_last_ack_fwd,omitempty"`
	TCPLastSeqRev              uint32           `binapi:"u32,name=tcp_last_seq_rev" json:"tcp_last_seq_rev,omitempty"`
	TCPLastAckRev              uint32           `binapi:"u32,name=tcp_last_ack_rev" json:"tcp_last_ack_rev,omitempty"`
	SessionVersion             uint32           `binapi:"u32,name=session_version" json:"session_version,omitempty"`
	TenantIdx                  uint32           `binapi:"u32,name=tenant_idx" json:"tenant_idx,omitempty"`
	SrcPort                    uint16           `binapi:"u16,name=src_port" json:"src_port,omitempty"`
	DstPort                    uint16           `binapi:"u16,name=dst_port" json:"dst_port,omitempty"`
	TCPMss                     uint16           `binapi:"u16,name=tcp_mss" json:"tcp_mss,omitempty"`
	Proto                      uint8            `binapi:"u8,name=proto" json:"proto,omitempty"`
	TTLMinFwd                  uint8            `binapi:"u8,name=ttl_min_fwd" json:"ttl_min_fwd,omitempty"`
	TTLMaxFwd                  uint8            `binapi:"u8,name=ttl_max_fwd" json:"ttl_max_fwd,omitempty"`
	TTLMinRev                  uint8            `binapi:"u8,name=ttl_min_rev" json:"ttl_min_rev,omitempty"`
	TTLMaxRev                  uint8            `binapi:"u8,name=ttl_max_rev" json:"ttl_max_rev,omitempty"`
	IsIP6                      bool             `binapi:"bool,name=is_ip6" json:"is_ip6,omitempty"`
	TCPHandshakeComplete       bool             `binapi:"bool,name=tcp_handshake_complete" json:"tcp_handshake_complete,omitempty"`
}

func (m *SfdpSessionStatsDetails) Reset()               { *m = SfdpSessionStatsDetails{} }
func (*SfdpSessionStatsDetails) GetMessageName() string { return "sfdp_session_stats_details" }
func (*SfdpSessionStatsDetails) GetCrcString() string   { return "653638b2" }
func (*SfdpSessionStatsDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpSessionStatsDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1      // m.SrcAddr.Af
	size += 1 * 16 // m.SrcAddr.Un
	size += 1      // m.DstAddr.Af
	size += 1 * 16 // m.DstAddr.Un
	size += 8      // m.FirstSeen
	size += 8      // m.LastSeen
	size += 8      // m.Duration
	size += 8      // m.TTLMeanFwd
	size += 8      // m.TTLMeanRev
	size += 8      // m.TTLStddevFwd
	size += 8      // m.TTLStddevRev
	size += 8      // m.RttMeanFwd
	size += 8      // m.RttMeanRev
	size += 8      // m.RttStddevFwd
	size += 8      // m.RttStddevRev
	size += 8      // m.PacketsFwd
	size += 8      // m.PacketsRev
	size += 8      // m.BytesFwd
	size += 8      // m.BytesRev
	size += 8      // m.SessionID
	size += 4      // m.TCPSynPackets
	size += 4      // m.TCPFinPackets
	size += 4      // m.TCPRstPackets
	size += 4      // m.TCPEcnEctPackets
	size += 4      // m.TCPEcnCePackets
	size += 4      // m.TCPEcePackets
	size += 4      // m.TCPCwrPackets
	size += 4      // m.TCPRetransmissionsFwd
	size += 4      // m.TCPRetransmissionsRev
	size += 4      // m.TCPZeroWindowEventsFwd
	size += 4      // m.TCPZeroWindowEventsRev
	size += 4      // m.TCPDupackEventsFwd
	size += 4      // m.TCPDupackEventsRev
	size += 4      // m.TCPPartialOverlapEventsFwd
	size += 4      // m.TCPPartialOverlapEventsRev
	size += 4      // m.TCPOutOfOrderEventsFwd
	size += 4      // m.TCPOutOfOrderEventsRev
	size += 4      // m.TCPLastSeqFwd
	size += 4      // m.TCPLastAckFwd
	size += 4      // m.TCPLastSeqRev
	size += 4      // m.TCPLastAckRev
	size += 4      // m.SessionVersion
	size += 4      // m.TenantIdx
	size += 2      // m.SrcPort
	size += 2      // m.DstPort
	size += 2      // m.TCPMss
	size += 1      // m.Proto
	size += 1      // m.TTLMinFwd
	size += 1      // m.TTLMaxFwd
	size += 1      // m.TTLMinRev
	size += 1      // m.TTLMaxRev
	size += 1      // m.IsIP6
	size += 1      // m.TCPHandshakeComplete
	return size
}
func (m *SfdpSessionStatsDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint8(uint8(m.SrcAddr.Af))
	buf.EncodeBytes(m.SrcAddr.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(uint8(m.DstAddr.Af))
	buf.EncodeBytes(m.DstAddr.Un.XXX_UnionData[:], 16)
	buf.EncodeFloat64(m.FirstSeen)
	buf.EncodeFloat64(m.LastSeen)
	buf.EncodeFloat64(m.Duration)
	buf.EncodeFloat64(m.TTLMeanFwd)
	buf.EncodeFloat64(m.TTLMeanRev)
	buf.EncodeFloat64(m.TTLStddevFwd)
	buf.EncodeFloat64(m.TTLStddevRev)
	buf.EncodeFloat64(m.RttMeanFwd)
	buf.EncodeFloat64(m.RttMeanRev)
	buf.EncodeFloat64(m.RttStddevFwd)
	buf.EncodeFloat64(m.RttStddevRev)
	buf.EncodeUint64(m.PacketsFwd)
	buf.EncodeUint64(m.PacketsRev)
	buf.EncodeUint64(m.BytesFwd)
	buf.EncodeUint64(m.BytesRev)
	buf.EncodeUint64(m.SessionID)
	buf.EncodeUint32(m.TCPSynPackets)
	buf.EncodeUint32(m.TCPFinPackets)
	buf.EncodeUint32(m.TCPRstPackets)
	buf.EncodeUint32(m.TCPEcnEctPackets)
	buf.EncodeUint32(m.TCPEcnCePackets)
	buf.EncodeUint32(m.TCPEcePackets)
	buf.EncodeUint32(m.TCPCwrPackets)
	buf.EncodeUint32(m.TCPRetransmissionsFwd)
	buf.EncodeUint32(m.TCPRetransmissionsRev)
	buf.EncodeUint32(m.TCPZeroWindowEventsFwd)
	buf.EncodeUint32(m.TCPZeroWindowEventsRev)
	buf.EncodeUint32(m.TCPDupackEventsFwd)
	buf.EncodeUint32(m.TCPDupackEventsRev)
	buf.EncodeUint32(m.TCPPartialOverlapEventsFwd)
	buf.EncodeUint32(m.TCPPartialOverlapEventsRev)
	buf.EncodeUint32(m.TCPOutOfOrderEventsFwd)
	buf.EncodeUint32(m.TCPOutOfOrderEventsRev)
	buf.EncodeUint32(m.TCPLastSeqFwd)
	buf.EncodeUint32(m.TCPLastAckFwd)
	buf.EncodeUint32(m.TCPLastSeqRev)
	buf.EncodeUint32(m.TCPLastAckRev)
	buf.EncodeUint32(m.SessionVersion)
	buf.EncodeUint32(m.TenantIdx)
	buf.EncodeUint16(m.SrcPort)
	buf.EncodeUint16(m.DstPort)
	buf.EncodeUint16(m.TCPMss)
	buf.EncodeUint8(m.Proto)
	buf.EncodeUint8(m.TTLMinFwd)
	buf.EncodeUint8(m.TTLMaxFwd)
	buf.EncodeUint8(m.TTLMinRev)
	buf.EncodeUint8(m.TTLMaxRev)
	buf.EncodeBool(m.IsIP6)
	buf.EncodeBool(m.TCPHandshakeComplete)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SrcAddr.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.SrcAddr.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.DstAddr.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.DstAddr.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.FirstSeen = buf.DecodeFloat64()
	m.LastSeen = buf.DecodeFloat64()
	m.Duration = buf.DecodeFloat64()
	m.TTLMeanFwd = buf.DecodeFloat64()
	m.TTLMeanRev = buf.DecodeFloat64()
	m.TTLStddevFwd = buf.DecodeFloat64()
	m.TTLStddevRev = buf.DecodeFloat64()
	m.RttMeanFwd = buf.DecodeFloat64()
	m.RttMeanRev = buf.DecodeFloat64()
	m.RttStddevFwd = buf.DecodeFloat64()
	m.RttStddevRev = buf.DecodeFloat64()
	m.PacketsFwd = buf.DecodeUint64()
	m.PacketsRev = buf.DecodeUint64()
	m.BytesFwd = buf.DecodeUint64()
	m.BytesRev = buf.DecodeUint64()
	m.SessionID = buf.DecodeUint64()
	m.TCPSynPackets = buf.DecodeUint32()
	m.TCPFinPackets = buf.DecodeUint32()
	m.TCPRstPackets = buf.DecodeUint32()
	m.TCPEcnEctPackets = buf.DecodeUint32()
	m.TCPEcnCePackets = buf.DecodeUint32()
	m.TCPEcePackets = buf.DecodeUint32()
	m.TCPCwrPackets = buf.DecodeUint32()
	m.TCPRetransmissionsFwd = buf.DecodeUint32()
	m.TCPRetransmissionsRev = buf.DecodeUint32()
	m.TCPZeroWindowEventsFwd = buf.DecodeUint32()
	m.TCPZeroWindowEventsRev = buf.DecodeUint32()
	m.TCPDupackEventsFwd = buf.DecodeUint32()
	m.TCPDupackEventsRev = buf.DecodeUint32()
	m.TCPPartialOverlapEventsFwd = buf.DecodeUint32()
	m.TCPPartialOverlapEventsRev = buf.DecodeUint32()
	m.TCPOutOfOrderEventsFwd = buf.DecodeUint32()
	m.TCPOutOfOrderEventsRev = buf.DecodeUint32()
	m.TCPLastSeqFwd = buf.DecodeUint32()
	m.TCPLastAckFwd = buf.DecodeUint32()
	m.TCPLastSeqRev = buf.DecodeUint32()
	m.TCPLastAckRev = buf.DecodeUint32()
	m.SessionVersion = buf.DecodeUint32()
	m.TenantIdx = buf.DecodeUint32()
	m.SrcPort = buf.DecodeUint16()
	m.DstPort = buf.DecodeUint16()
	m.TCPMss = buf.DecodeUint16()
	m.Proto = buf.DecodeUint8()
	m.TTLMinFwd = buf.DecodeUint8()
	m.TTLMaxFwd = buf.DecodeUint8()
	m.TTLMinRev = buf.DecodeUint8()
	m.TTLMaxRev = buf.DecodeUint8()
	m.IsIP6 = buf.DecodeBool()
	m.TCPHandshakeComplete = buf.DecodeBool()
	return nil
}

// * @brief Request session stats dump
//   - - session_id - specific session ID to dump (0 = all sessions)
//   - - tenant_idx - filter by tenant (0xFFFFFFFF = all tenants)
//
// SfdpSessionStatsDump defines message 'sfdp_session_stats_dump'.
type SfdpSessionStatsDump struct {
	SessionID uint64 `binapi:"u64,name=session_id,default=0" json:"session_id,omitempty"`
	TenantIdx uint32 `binapi:"u32,name=tenant_idx,default=4294967295" json:"tenant_idx,omitempty"`
}

func (m *SfdpSessionStatsDump) Reset()               { *m = SfdpSessionStatsDump{} }
func (*SfdpSessionStatsDump) GetMessageName() string { return "sfdp_session_stats_dump" }
func (*SfdpSessionStatsDump) GetCrcString() string   { return "c308c73e" }
func (*SfdpSessionStatsDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpSessionStatsDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 8 // m.SessionID
	size += 4 // m.TenantIdx
	return size
}
func (m *SfdpSessionStatsDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint64(m.SessionID)
	buf.EncodeUint32(m.TenantIdx)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SessionID = buf.DecodeUint64()
	m.TenantIdx = buf.DecodeUint32()
	return nil
}

// * @brief Trigger immediate export of all sessions to ring buffer
// SfdpSessionStatsExportNow defines message 'sfdp_session_stats_export_now'.
type SfdpSessionStatsExportNow struct{}

func (m *SfdpSessionStatsExportNow) Reset()               { *m = SfdpSessionStatsExportNow{} }
func (*SfdpSessionStatsExportNow) GetMessageName() string { return "sfdp_session_stats_export_now" }
func (*SfdpSessionStatsExportNow) GetCrcString() string   { return "51077d14" }
func (*SfdpSessionStatsExportNow) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpSessionStatsExportNow) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *SfdpSessionStatsExportNow) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsExportNow) Unmarshal(b []byte) error {
	return nil
}

// SfdpSessionStatsExportNowReply defines message 'sfdp_session_stats_export_now_reply'.
type SfdpSessionStatsExportNowReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *SfdpSessionStatsExportNowReply) Reset() { *m = SfdpSessionStatsExportNowReply{} }
func (*SfdpSessionStatsExportNowReply) GetMessageName() string {
	return "sfdp_session_stats_export_now_reply"
}
func (*SfdpSessionStatsExportNowReply) GetCrcString() string { return "e8d4e804" }
func (*SfdpSessionStatsExportNowReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpSessionStatsExportNowReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *SfdpSessionStatsExportNowReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsExportNowReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// * @brief Get session stats global configuration
// SfdpSessionStatsGetConfig defines message 'sfdp_session_stats_get_config'.
type SfdpSessionStatsGetConfig struct{}

func (m *SfdpSessionStatsGetConfig) Reset()               { *m = SfdpSessionStatsGetConfig{} }
func (*SfdpSessionStatsGetConfig) GetMessageName() string { return "sfdp_session_stats_get_config" }
func (*SfdpSessionStatsGetConfig) GetCrcString() string   { return "51077d14" }
func (*SfdpSessionStatsGetConfig) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpSessionStatsGetConfig) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *SfdpSessionStatsGetConfig) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsGetConfig) Unmarshal(b []byte) error {
	return nil
}

// * @brief Session stats configuration reply
//   - - ring_buffer_enabled - whether ring buffer is enabled
//   - - periodic_export_enabled - whether periodic export is enabled
//   - - export_interval - current export interval in seconds
//   - - export_batch_interval - current export batch interval in seconds
//   - - ring_size - configured ring buffer size
//   - - total_exports - total number of exports performed
//   - - active_sessions - number of active sessions being tracked
//
// SfdpSessionStatsGetConfigReply defines message 'sfdp_session_stats_get_config_reply'.
type SfdpSessionStatsGetConfigReply struct {
	Retval                int32   `binapi:"i32,name=retval" json:"retval,omitempty"`
	RingBufferEnabled     bool    `binapi:"bool,name=ring_buffer_enabled" json:"ring_buffer_enabled,omitempty"`
	PeriodicExportEnabled bool    `binapi:"bool,name=periodic_export_enabled" json:"periodic_export_enabled,omitempty"`
	ExportInterval        float64 `binapi:"f64,name=export_interval" json:"export_interval,omitempty"`
	ExportBatchInterval   float64 `binapi:"f64,name=export_batch_interval" json:"export_batch_interval,omitempty"`
	RingSize              uint32  `binapi:"u32,name=ring_size" json:"ring_size,omitempty"`
	TotalExports          uint64  `binapi:"u64,name=total_exports" json:"total_exports,omitempty"`
	ActiveSessions        uint32  `binapi:"u32,name=active_sessions" json:"active_sessions,omitempty"`
}

func (m *SfdpSessionStatsGetConfigReply) Reset() { *m = SfdpSessionStatsGetConfigReply{} }
func (*SfdpSessionStatsGetConfigReply) GetMessageName() string {
	return "sfdp_session_stats_get_config_reply"
}
func (*SfdpSessionStatsGetConfigReply) GetCrcString() string { return "77eac48b" }
func (*SfdpSessionStatsGetConfigReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpSessionStatsGetConfigReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	size += 1 // m.RingBufferEnabled
	size += 1 // m.PeriodicExportEnabled
	size += 8 // m.ExportInterval
	size += 8 // m.ExportBatchInterval
	size += 4 // m.RingSize
	size += 8 // m.TotalExports
	size += 4 // m.ActiveSessions
	return size
}
func (m *SfdpSessionStatsGetConfigReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeBool(m.RingBufferEnabled)
	buf.EncodeBool(m.PeriodicExportEnabled)
	buf.EncodeFloat64(m.ExportInterval)
	buf.EncodeFloat64(m.ExportBatchInterval)
	buf.EncodeUint32(m.RingSize)
	buf.EncodeUint64(m.TotalExports)
	buf.EncodeUint32(m.ActiveSessions)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsGetConfigReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.RingBufferEnabled = buf.DecodeBool()
	m.PeriodicExportEnabled = buf.DecodeBool()
	m.ExportInterval = buf.DecodeFloat64()
	m.ExportBatchInterval = buf.DecodeFloat64()
	m.RingSize = buf.DecodeUint32()
	m.TotalExports = buf.DecodeUint64()
	m.ActiveSessions = buf.DecodeUint32()
	return nil
}

// * @brief Get custom data configuration for a specific tenant
//   - - tenant_id - tenant ID (customer-specified value) to query
//
// SfdpSessionStatsGetTenantCustomData defines message 'sfdp_session_stats_get_tenant_custom_data'.
type SfdpSessionStatsGetTenantCustomData struct {
	TenantID uint32 `binapi:"u32,name=tenant_id" json:"tenant_id,omitempty"`
}

func (m *SfdpSessionStatsGetTenantCustomData) Reset() { *m = SfdpSessionStatsGetTenantCustomData{} }
func (*SfdpSessionStatsGetTenantCustomData) GetMessageName() string {
	return "sfdp_session_stats_get_tenant_custom_data"
}
func (*SfdpSessionStatsGetTenantCustomData) GetCrcString() string { return "09d55da7" }
func (*SfdpSessionStatsGetTenantCustomData) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpSessionStatsGetTenantCustomData) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.TenantID
	return size
}
func (m *SfdpSessionStatsGetTenantCustomData) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TenantID)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsGetTenantCustomData) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TenantID = buf.DecodeUint32()
	return nil
}

// * @brief Tenant custom data configuration reply
//   - - tenant_id - tenant ID queried
//   - - has_api_data - whether API custom data is set for this tenant
//   - - api_data_value - current API custom data value (0 if not set)
//
// SfdpSessionStatsGetTenantCustomDataReply defines message 'sfdp_session_stats_get_tenant_custom_data_reply'.
type SfdpSessionStatsGetTenantCustomDataReply struct {
	Retval       int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	TenantID     uint32 `binapi:"u32,name=tenant_id" json:"tenant_id,omitempty"`
	HasAPIData   bool   `binapi:"bool,name=has_api_data" json:"has_api_data,omitempty"`
	APIDataValue uint64 `binapi:"u64,name=api_data_value" json:"api_data_value,omitempty"`
}

func (m *SfdpSessionStatsGetTenantCustomDataReply) Reset() {
	*m = SfdpSessionStatsGetTenantCustomDataReply{}
}
func (*SfdpSessionStatsGetTenantCustomDataReply) GetMessageName() string {
	return "sfdp_session_stats_get_tenant_custom_data_reply"
}
func (*SfdpSessionStatsGetTenantCustomDataReply) GetCrcString() string { return "5c075284" }
func (*SfdpSessionStatsGetTenantCustomDataReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpSessionStatsGetTenantCustomDataReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	size += 4 // m.TenantID
	size += 1 // m.HasAPIData
	size += 8 // m.APIDataValue
	return size
}
func (m *SfdpSessionStatsGetTenantCustomDataReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(m.TenantID)
	buf.EncodeBool(m.HasAPIData)
	buf.EncodeUint64(m.APIDataValue)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsGetTenantCustomDataReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.TenantID = buf.DecodeUint32()
	m.HasAPIData = buf.DecodeBool()
	m.APIDataValue = buf.DecodeUint64()
	return nil
}

// * @brief Configure periodic export
//   - - enable - 1 to enable, 0 to disable periodic export
//   - - interval - export interval in seconds
//   - - batch_interval - export batch interval in seconds
//
// SfdpSessionStatsPeriodicExport defines message 'sfdp_session_stats_periodic_export'.
type SfdpSessionStatsPeriodicExport struct {
	Enable        bool    `binapi:"bool,name=enable,default=true" json:"enable,omitempty"`
	Interval      float64 `binapi:"f64,name=interval,default=30" json:"interval,omitempty"`
	BatchInterval float64 `binapi:"f64,name=batch_interval,default=1" json:"batch_interval,omitempty"`
}

func (m *SfdpSessionStatsPeriodicExport) Reset() { *m = SfdpSessionStatsPeriodicExport{} }
func (*SfdpSessionStatsPeriodicExport) GetMessageName() string {
	return "sfdp_session_stats_periodic_export"
}
func (*SfdpSessionStatsPeriodicExport) GetCrcString() string { return "fc6c0af7" }
func (*SfdpSessionStatsPeriodicExport) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpSessionStatsPeriodicExport) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 // m.Enable
	size += 8 // m.Interval
	size += 8 // m.BatchInterval
	return size
}
func (m *SfdpSessionStatsPeriodicExport) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.Enable)
	buf.EncodeFloat64(m.Interval)
	buf.EncodeFloat64(m.BatchInterval)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsPeriodicExport) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Enable = buf.DecodeBool()
	m.Interval = buf.DecodeFloat64()
	m.BatchInterval = buf.DecodeFloat64()
	return nil
}

// SfdpSessionStatsPeriodicExportReply defines message 'sfdp_session_stats_periodic_export_reply'.
type SfdpSessionStatsPeriodicExportReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *SfdpSessionStatsPeriodicExportReply) Reset() { *m = SfdpSessionStatsPeriodicExportReply{} }
func (*SfdpSessionStatsPeriodicExportReply) GetMessageName() string {
	return "sfdp_session_stats_periodic_export_reply"
}
func (*SfdpSessionStatsPeriodicExportReply) GetCrcString() string { return "e8d4e804" }
func (*SfdpSessionStatsPeriodicExportReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpSessionStatsPeriodicExportReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *SfdpSessionStatsPeriodicExportReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsPeriodicExportReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// * @brief Enable/disable the session stats ring buffer
//   - - enable - 1 to enable, 0 to disable
//   - - ring_size - size of the ring buffer (number of entries)
//
// SfdpSessionStatsRingEnable defines message 'sfdp_session_stats_ring_enable'.
type SfdpSessionStatsRingEnable struct {
	Enable   bool   `binapi:"bool,name=enable,default=true" json:"enable,omitempty"`
	RingSize uint32 `binapi:"u32,name=ring_size,default=4096" json:"ring_size,omitempty"`
}

func (m *SfdpSessionStatsRingEnable) Reset()               { *m = SfdpSessionStatsRingEnable{} }
func (*SfdpSessionStatsRingEnable) GetMessageName() string { return "sfdp_session_stats_ring_enable" }
func (*SfdpSessionStatsRingEnable) GetCrcString() string   { return "d9045ab0" }
func (*SfdpSessionStatsRingEnable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpSessionStatsRingEnable) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 // m.Enable
	size += 4 // m.RingSize
	return size
}
func (m *SfdpSessionStatsRingEnable) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.Enable)
	buf.EncodeUint32(m.RingSize)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsRingEnable) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Enable = buf.DecodeBool()
	m.RingSize = buf.DecodeUint32()
	return nil
}

// SfdpSessionStatsRingEnableReply defines message 'sfdp_session_stats_ring_enable_reply'.
type SfdpSessionStatsRingEnableReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *SfdpSessionStatsRingEnableReply) Reset() { *m = SfdpSessionStatsRingEnableReply{} }
func (*SfdpSessionStatsRingEnableReply) GetMessageName() string {
	return "sfdp_session_stats_ring_enable_reply"
}
func (*SfdpSessionStatsRingEnableReply) GetCrcString() string { return "e8d4e804" }
func (*SfdpSessionStatsRingEnableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpSessionStatsRingEnableReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *SfdpSessionStatsRingEnableReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsRingEnableReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// /*
//   - marker message whose abi_id is shared in ring-buffer schema
//   - to allow consumers to verify version match with
//   - typedef 'sfdp_session_stats_ring_entry'
//
// SfdpSessionStatsRingEntryAbiID defines message 'sfdp_session_stats_ring_entry_abi_id'.
type SfdpSessionStatsRingEntryAbiID struct {
	Entry SfdpSessionStatsRingEntry `binapi:"sfdp_session_stats_ring_entry,name=entry" json:"entry,omitempty"`
}

func (m *SfdpSessionStatsRingEntryAbiID) Reset() { *m = SfdpSessionStatsRingEntryAbiID{} }
func (*SfdpSessionStatsRingEntryAbiID) GetMessageName() string {
	return "sfdp_session_stats_ring_entry_abi_id"
}
func (*SfdpSessionStatsRingEntryAbiID) GetCrcString() string { return "a8316c49" }
func (*SfdpSessionStatsRingEntryAbiID) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpSessionStatsRingEntryAbiID) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 8      // m.Entry.Duration
	size += 8      // m.Entry.TTLMeanForward
	size += 8      // m.Entry.TTLMeanReverse
	size += 8      // m.Entry.TTLStddevForward
	size += 8      // m.Entry.TTLStddevReverse
	size += 8      // m.Entry.RttMeanForward
	size += 8      // m.Entry.RttMeanReverse
	size += 8      // m.Entry.RttStddevForward
	size += 8      // m.Entry.RttStddevReverse
	size += 8      // m.Entry.SessionID
	size += 8      // m.Entry.PacketsForward
	size += 8      // m.Entry.PacketsReverse
	size += 8      // m.Entry.BytesForward
	size += 8      // m.Entry.BytesReverse
	size += 8      // m.Entry.Opaque
	size += 4      // m.Entry.SessionIndex
	size += 4      // m.Entry.TenantID
	size += 4      // m.Entry.TCPSynPackets
	size += 4      // m.Entry.TCPFinPackets
	size += 4      // m.Entry.TCPRstPackets
	size += 4      // m.Entry.TCPEcnEctPackets
	size += 4      // m.Entry.TCPEcnCePackets
	size += 4      // m.Entry.TCPEcePackets
	size += 4      // m.Entry.TCPCwrPackets
	size += 4      // m.Entry.TCPRetransmissionsFwd
	size += 4      // m.Entry.TCPRetransmissionsRev
	size += 4      // m.Entry.TCPZeroWindowEventsFwd
	size += 4      // m.Entry.TCPZeroWindowEventsRev
	size += 4      // m.Entry.TCPDupackEventsFwd
	size += 4      // m.Entry.TCPDupackEventsRev
	size += 4      // m.Entry.TCPPartialOverlapEventsFwd
	size += 4      // m.Entry.TCPPartialOverlapEventsRev
	size += 4      // m.Entry.TCPOutOfOrderEventsFwd
	size += 4      // m.Entry.TCPOutOfOrderEventsRev
	size += 4      // m.Entry.TCPLastSeqForward
	size += 4      // m.Entry.TCPLastAckForward
	size += 4      // m.Entry.TCPLastSeqReverse
	size += 4      // m.Entry.TCPLastAckReverse
	size += 2      // m.Entry.SrcPort
	size += 2      // m.Entry.DstPort
	size += 2      // m.Entry.TCPMss
	size += 1      // m.Entry.Proto
	size += 1      // m.Entry.SessionType
	size += 1      // m.Entry.IsIP4
	size += 1      // m.Entry.TTLMinForward
	size += 1      // m.Entry.TTLMaxForward
	size += 1      // m.Entry.TTLMinReverse
	size += 1      // m.Entry.TTLMaxReverse
	size += 1 * 16 // m.Entry.SrcIP
	size += 1 * 16 // m.Entry.DstIP
	size += 1      // m.Entry.TCPHandshakeComplete
	return size
}
func (m *SfdpSessionStatsRingEntryAbiID) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeFloat64(m.Entry.Duration)
	buf.EncodeFloat64(m.Entry.TTLMeanForward)
	buf.EncodeFloat64(m.Entry.TTLMeanReverse)
	buf.EncodeFloat64(m.Entry.TTLStddevForward)
	buf.EncodeFloat64(m.Entry.TTLStddevReverse)
	buf.EncodeFloat64(m.Entry.RttMeanForward)
	buf.EncodeFloat64(m.Entry.RttMeanReverse)
	buf.EncodeFloat64(m.Entry.RttStddevForward)
	buf.EncodeFloat64(m.Entry.RttStddevReverse)
	buf.EncodeUint64(m.Entry.SessionID)
	buf.EncodeUint64(m.Entry.PacketsForward)
	buf.EncodeUint64(m.Entry.PacketsReverse)
	buf.EncodeUint64(m.Entry.BytesForward)
	buf.EncodeUint64(m.Entry.BytesReverse)
	buf.EncodeUint64(m.Entry.Opaque)
	buf.EncodeUint32(m.Entry.SessionIndex)
	buf.EncodeUint32(m.Entry.TenantID)
	buf.EncodeUint32(m.Entry.TCPSynPackets)
	buf.EncodeUint32(m.Entry.TCPFinPackets)
	buf.EncodeUint32(m.Entry.TCPRstPackets)
	buf.EncodeUint32(m.Entry.TCPEcnEctPackets)
	buf.EncodeUint32(m.Entry.TCPEcnCePackets)
	buf.EncodeUint32(m.Entry.TCPEcePackets)
	buf.EncodeUint32(m.Entry.TCPCwrPackets)
	buf.EncodeUint32(m.Entry.TCPRetransmissionsFwd)
	buf.EncodeUint32(m.Entry.TCPRetransmissionsRev)
	buf.EncodeUint32(m.Entry.TCPZeroWindowEventsFwd)
	buf.EncodeUint32(m.Entry.TCPZeroWindowEventsRev)
	buf.EncodeUint32(m.Entry.TCPDupackEventsFwd)
	buf.EncodeUint32(m.Entry.TCPDupackEventsRev)
	buf.EncodeUint32(m.Entry.TCPPartialOverlapEventsFwd)
	buf.EncodeUint32(m.Entry.TCPPartialOverlapEventsRev)
	buf.EncodeUint32(m.Entry.TCPOutOfOrderEventsFwd)
	buf.EncodeUint32(m.Entry.TCPOutOfOrderEventsRev)
	buf.EncodeUint32(m.Entry.TCPLastSeqForward)
	buf.EncodeUint32(m.Entry.TCPLastAckForward)
	buf.EncodeUint32(m.Entry.TCPLastSeqReverse)
	buf.EncodeUint32(m.Entry.TCPLastAckReverse)
	buf.EncodeUint16(m.Entry.SrcPort)
	buf.EncodeUint16(m.Entry.DstPort)
	buf.EncodeUint16(m.Entry.TCPMss)
	buf.EncodeUint8(m.Entry.Proto)
	buf.EncodeUint8(m.Entry.SessionType)
	buf.EncodeUint8(m.Entry.IsIP4)
	buf.EncodeUint8(m.Entry.TTLMinForward)
	buf.EncodeUint8(m.Entry.TTLMaxForward)
	buf.EncodeUint8(m.Entry.TTLMinReverse)
	buf.EncodeUint8(m.Entry.TTLMaxReverse)
	buf.EncodeBytes(m.Entry.SrcIP, 16)
	buf.EncodeBytes(m.Entry.DstIP, 16)
	buf.EncodeUint8(m.Entry.TCPHandshakeComplete)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsRingEntryAbiID) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Entry.Duration = buf.DecodeFloat64()
	m.Entry.TTLMeanForward = buf.DecodeFloat64()
	m.Entry.TTLMeanReverse = buf.DecodeFloat64()
	m.Entry.TTLStddevForward = buf.DecodeFloat64()
	m.Entry.TTLStddevReverse = buf.DecodeFloat64()
	m.Entry.RttMeanForward = buf.DecodeFloat64()
	m.Entry.RttMeanReverse = buf.DecodeFloat64()
	m.Entry.RttStddevForward = buf.DecodeFloat64()
	m.Entry.RttStddevReverse = buf.DecodeFloat64()
	m.Entry.SessionID = buf.DecodeUint64()
	m.Entry.PacketsForward = buf.DecodeUint64()
	m.Entry.PacketsReverse = buf.DecodeUint64()
	m.Entry.BytesForward = buf.DecodeUint64()
	m.Entry.BytesReverse = buf.DecodeUint64()
	m.Entry.Opaque = buf.DecodeUint64()
	m.Entry.SessionIndex = buf.DecodeUint32()
	m.Entry.TenantID = buf.DecodeUint32()
	m.Entry.TCPSynPackets = buf.DecodeUint32()
	m.Entry.TCPFinPackets = buf.DecodeUint32()
	m.Entry.TCPRstPackets = buf.DecodeUint32()
	m.Entry.TCPEcnEctPackets = buf.DecodeUint32()
	m.Entry.TCPEcnCePackets = buf.DecodeUint32()
	m.Entry.TCPEcePackets = buf.DecodeUint32()
	m.Entry.TCPCwrPackets = buf.DecodeUint32()
	m.Entry.TCPRetransmissionsFwd = buf.DecodeUint32()
	m.Entry.TCPRetransmissionsRev = buf.DecodeUint32()
	m.Entry.TCPZeroWindowEventsFwd = buf.DecodeUint32()
	m.Entry.TCPZeroWindowEventsRev = buf.DecodeUint32()
	m.Entry.TCPDupackEventsFwd = buf.DecodeUint32()
	m.Entry.TCPDupackEventsRev = buf.DecodeUint32()
	m.Entry.TCPPartialOverlapEventsFwd = buf.DecodeUint32()
	m.Entry.TCPPartialOverlapEventsRev = buf.DecodeUint32()
	m.Entry.TCPOutOfOrderEventsFwd = buf.DecodeUint32()
	m.Entry.TCPOutOfOrderEventsRev = buf.DecodeUint32()
	m.Entry.TCPLastSeqForward = buf.DecodeUint32()
	m.Entry.TCPLastAckForward = buf.DecodeUint32()
	m.Entry.TCPLastSeqReverse = buf.DecodeUint32()
	m.Entry.TCPLastAckReverse = buf.DecodeUint32()
	m.Entry.SrcPort = buf.DecodeUint16()
	m.Entry.DstPort = buf.DecodeUint16()
	m.Entry.TCPMss = buf.DecodeUint16()
	m.Entry.Proto = buf.DecodeUint8()
	m.Entry.SessionType = buf.DecodeUint8()
	m.Entry.IsIP4 = buf.DecodeUint8()
	m.Entry.TTLMinForward = buf.DecodeUint8()
	m.Entry.TTLMaxForward = buf.DecodeUint8()
	m.Entry.TTLMinReverse = buf.DecodeUint8()
	m.Entry.TTLMaxReverse = buf.DecodeUint8()
	m.Entry.SrcIP = make([]byte, 16)
	copy(m.Entry.SrcIP, buf.DecodeBytes(len(m.Entry.SrcIP)))
	m.Entry.DstIP = make([]byte, 16)
	copy(m.Entry.DstIP, buf.DecodeBytes(len(m.Entry.DstIP)))
	m.Entry.TCPHandshakeComplete = buf.DecodeUint8()
	return nil
}

// SfdpSessionStatsRingEntryAbiIDReply defines message 'sfdp_session_stats_ring_entry_abi_id_reply'.
type SfdpSessionStatsRingEntryAbiIDReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *SfdpSessionStatsRingEntryAbiIDReply) Reset() { *m = SfdpSessionStatsRingEntryAbiIDReply{} }
func (*SfdpSessionStatsRingEntryAbiIDReply) GetMessageName() string {
	return "sfdp_session_stats_ring_entry_abi_id_reply"
}
func (*SfdpSessionStatsRingEntryAbiIDReply) GetCrcString() string { return "e8d4e804" }
func (*SfdpSessionStatsRingEntryAbiIDReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpSessionStatsRingEntryAbiIDReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *SfdpSessionStatsRingEntryAbiIDReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsRingEntryAbiIDReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// * @brief Set custom API data value for a tenant
//   - This value will be included in the opaque field of each exported
//   - session entry for the specified tenant.
//   - If no custom data is set for a tenant, the exported opaque value is 0.
//     *
//   - - tenant_id - tenant ID (customer-specified value) to set custom data for
//   - - value - the u64 value to set
//
// SfdpSessionStatsSetCustomAPIData defines message 'sfdp_session_stats_set_custom_api_data'.
type SfdpSessionStatsSetCustomAPIData struct {
	TenantID uint32 `binapi:"u32,name=tenant_id" json:"tenant_id,omitempty"`
	Value    uint64 `binapi:"u64,name=value" json:"value,omitempty"`
}

func (m *SfdpSessionStatsSetCustomAPIData) Reset() { *m = SfdpSessionStatsSetCustomAPIData{} }
func (*SfdpSessionStatsSetCustomAPIData) GetMessageName() string {
	return "sfdp_session_stats_set_custom_api_data"
}
func (*SfdpSessionStatsSetCustomAPIData) GetCrcString() string { return "982dd0b2" }
func (*SfdpSessionStatsSetCustomAPIData) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpSessionStatsSetCustomAPIData) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.TenantID
	size += 8 // m.Value
	return size
}
func (m *SfdpSessionStatsSetCustomAPIData) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TenantID)
	buf.EncodeUint64(m.Value)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsSetCustomAPIData) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TenantID = buf.DecodeUint32()
	m.Value = buf.DecodeUint64()
	return nil
}

// SfdpSessionStatsSetCustomAPIDataReply defines message 'sfdp_session_stats_set_custom_api_data_reply'.
type SfdpSessionStatsSetCustomAPIDataReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *SfdpSessionStatsSetCustomAPIDataReply) Reset() { *m = SfdpSessionStatsSetCustomAPIDataReply{} }
func (*SfdpSessionStatsSetCustomAPIDataReply) GetMessageName() string {
	return "sfdp_session_stats_set_custom_api_data_reply"
}
func (*SfdpSessionStatsSetCustomAPIDataReply) GetCrcString() string { return "e8d4e804" }
func (*SfdpSessionStatsSetCustomAPIDataReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpSessionStatsSetCustomAPIDataReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *SfdpSessionStatsSetCustomAPIDataReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *SfdpSessionStatsSetCustomAPIDataReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

func init() { file_session_stats_binapi_init() }
func file_session_stats_binapi_init() {
	api.RegisterMessage((*SfdpSessionStatsClear)(nil), "sfdp_session_stats_clear_350f1aaa")
	api.RegisterMessage((*SfdpSessionStatsClearCustomAPIData)(nil), "sfdp_session_stats_clear_custom_api_data_09d55da7")
	api.RegisterMessage((*SfdpSessionStatsClearCustomAPIDataReply)(nil), "sfdp_session_stats_clear_custom_api_data_reply_e8d4e804")
	api.RegisterMessage((*SfdpSessionStatsClearReply)(nil), "sfdp_session_stats_clear_reply_e8d4e804")
	api.RegisterMessage((*SfdpSessionStatsDetails)(nil), "sfdp_session_stats_details_653638b2")
	api.RegisterMessage((*SfdpSessionStatsDump)(nil), "sfdp_session_stats_dump_c308c73e")
	api.RegisterMessage((*SfdpSessionStatsExportNow)(nil), "sfdp_session_stats_export_now_51077d14")
	api.RegisterMessage((*SfdpSessionStatsExportNowReply)(nil), "sfdp_session_stats_export_now_reply_e8d4e804")
	api.RegisterMessage((*SfdpSessionStatsGetConfig)(nil), "sfdp_session_stats_get_config_51077d14")
	api.RegisterMessage((*SfdpSessionStatsGetConfigReply)(nil), "sfdp_session_stats_get_config_reply_77eac48b")
	api.RegisterMessage((*SfdpSessionStatsGetTenantCustomData)(nil), "sfdp_session_stats_get_tenant_custom_data_09d55da7")
	api.RegisterMessage((*SfdpSessionStatsGetTenantCustomDataReply)(nil), "sfdp_session_stats_get_tenant_custom_data_reply_5c075284")
	api.RegisterMessage((*SfdpSessionStatsPeriodicExport)(nil), "sfdp_session_stats_periodic_export_fc6c0af7")
	api.RegisterMessage((*SfdpSessionStatsPeriodicExportReply)(nil), "sfdp_session_stats_periodic_export_reply_e8d4e804")
	api.RegisterMessage((*SfdpSessionStatsRingEnable)(nil), "sfdp_session_stats_ring_enable_d9045ab0")
	api.RegisterMessage((*SfdpSessionStatsRingEnableReply)(nil), "sfdp_session_stats_ring_enable_reply_e8d4e804")
	api.RegisterMessage((*SfdpSessionStatsRingEntryAbiID)(nil), "sfdp_session_stats_ring_entry_abi_id_a8316c49")
	api.RegisterMessage((*SfdpSessionStatsRingEntryAbiIDReply)(nil), "sfdp_session_stats_ring_entry_abi_id_reply_e8d4e804")
	api.RegisterMessage((*SfdpSessionStatsSetCustomAPIData)(nil), "sfdp_session_stats_set_custom_api_data_982dd0b2")
	api.RegisterMessage((*SfdpSessionStatsSetCustomAPIDataReply)(nil), "sfdp_session_stats_set_custom_api_data_reply_e8d4e804")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*SfdpSessionStatsClear)(nil),
		(*SfdpSessionStatsClearCustomAPIData)(nil),
		(*SfdpSessionStatsClearCustomAPIDataReply)(nil),
		(*SfdpSessionStatsClearReply)(nil),
		(*SfdpSessionStatsDetails)(nil),
		(*SfdpSessionStatsDump)(nil),
		(*SfdpSessionStatsExportNow)(nil),
		(*SfdpSessionStatsExportNowReply)(nil),
		(*SfdpSessionStatsGetConfig)(nil),
		(*SfdpSessionStatsGetConfigReply)(nil),
		(*SfdpSessionStatsGetTenantCustomData)(nil),
		(*SfdpSessionStatsGetTenantCustomDataReply)(nil),
		(*SfdpSessionStatsPeriodicExport)(nil),
		(*SfdpSessionStatsPeriodicExportReply)(nil),
		(*SfdpSessionStatsRingEnable)(nil),
		(*SfdpSessionStatsRingEnableReply)(nil),
		(*SfdpSessionStatsRingEntryAbiID)(nil),
		(*SfdpSessionStatsRingEntryAbiIDReply)(nil),
		(*SfdpSessionStatsSetCustomAPIData)(nil),
		(*SfdpSessionStatsSetCustomAPIDataReply)(nil),
	}
}
